on:
  push:
    branches:
      - prod
name:  🚀 Deploy
jobs:
  FTP-Deploy-Action:
    name:  🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1
      
      # - name: Install PHP
      #   uses: shivammathur/setup-php@v2
      #   with:
      #     php-version: 8.2.8

      # - name: Install Composer dependencies
      #   run: composer install --prefer-dist --no-progress --no-dev


      - name: Laravel Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # local-dir: API/
          exclude: |
            **/.git*
            **/.git*/**

          
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: |
            "Walkbuddy Project Backend Deployed 🚀"